%% PIPELINE
% 1) Data is imported
% 2) Data is preprocessed (notch and high-pass filtered at 0.3 Hz, cleaned
%    from ECG artifacts)
% 3) Preprocessed data is resampled and divided into epochs
% 4) Sources are estimated from each epoch
% 5) Scouts are extracted from such sources
% 6) Sources are reprojected from a subject onto other subject's cortices
% 7) Scouts are extracted from reprojected sources


bsDir = 'C:\Users\simon\OneDrive\Desktop\Ricerca\EEGLab\';
inDir = 'D:\MEG\fp';
outDir = 'D:\MEG\fp\results';
ProtocolName = 'fp';
epTime = 2;
EventsTimeRange = [-0.1, 3];
condition = '_task-rest_meg_clean_resample_high';
srcType = 'amplitude';
removeBadEpochs = 1;
commonFLAG = 1; % Takes the minimum number of epochs per subject
epMax = 52;

scout = 'Desikan-Killiany';
ROIs = {'bankssts L','bankssts R','caudalanteriorcingulate L',...
        'caudalanteriorcingulate R','caudalmiddlefrontal L',...
        'caudalmiddlefrontal R','cuneus L','cuneus R',...
        'entorhinal L','entorhinal R','frontalpole L','frontalpole R',...
        'fusiform L','fusiform R','inferiorparietal L',...
        'inferiorparietal R','inferiortemporal L','inferiortemporal R',...
        'insula L','insula R','isthmuscingulate L',...
        'isthmuscingulate R','lateraloccipital L','lateraloccipital R',...
        'lateralorbitofrontal L','lateralorbitofrontal R','lingual L',...
        'lingual R','medialorbitofrontal L','medialorbitofrontal R',...
        'middletemporal L','middletemporal R','paracentral L',...
        'paracentral R','parahippocampal L','parahippocampal R',...
        'parsopercularis L','parsopercularis R','parsorbitalis L',...
        'parsorbitalis R','parstriangularis L','parstriangularis R',...
        'pericalcarine L','pericalcarine R','postcentral L',...
        'postcentral R','posteriorcingulate L','posteriorcingulate R',...
        'precentral L','precentral R','precuneus L','precuneus R',...
        'rostralanteriorcingulate L','rostralanteriorcingulate R',...
        'rostralmiddlefrontal L','rostralmiddlefrontal R',...
        'superiorfrontal L','superiorfrontal R','superiorparietal L',...
        'superiorparietal R','superiortemporal L','superiortemporal R',...
        'supramarginal L','supramarginal R','temporalpole L',...
        'temporalpole R','transversetemporal L','transversetemporal R'};

%[rawFiles, fs, t] = initialization(ProtocolName, inDir, bsDir, epTime);
if ~brainstorm('status')
    brainstorm nogui
end
importFiles = fp_import_files(strcat(inDir, filesep, ProtocolName), ...
    epTime, removeBadEpochs, commonFLAG, epMax);
sourceFiles = source_estimation(importFiles, 1, srcType);
scoutFiles = scout_extraction(sourceFiles, scout, ROIs, inDir, ...
    ProtocolName, outDir);
N = length(importFiles);
for i = 1:N
    srcSubject = importFiles{i}(1).FileName(1:9);
    newSourceFiles = sources_projection(sourceFiles, srcSubject, ...
        inDir, ProtocolName, condition, srcType);
    scout_extraction_reprojected(newSourceFiles, ...
        scout, ROIs, srcSubject, epTime, inDir, ProtocolName, outDir);
end
%psdSourcesFiles = power_maps(sourceFiles);

disp(1)   
    